CREATE TABLE BOARDE(
    NUM NUMBER(20) NOT NULL PRIMARY KEY,
    WRITER VARCHAR2(15),
    EMAIL VARCHAR2(30),
    SUBJECT VARCHAR2(75),
    PASSWD VARCHAR(12) NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    READCNT NUMBER DEFAULT 0,
    REF NUMBER(20) NOT NULL,
    RE_STEP NUMBER(10) NOT NULL,
    RE_LEVEL NUMBER(10) NOT NULL,
    CONTENT VARCHAR(3000) NOT NULL,
    IP VARCHAR(20) NOT NULL
);

SELECT*FROM BOARDE;
delete boarde;
COMMIT;


CREATE SEQUENCE SEQ_BOARDE_NUM
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999999999999999
    NOCYCLE
;
DROP SEQUENCE SEQ_BOARDE_NUM;

DROP TABLE BOARDE;

ALTER SEQUENCE SEQ_BOARDE_NUM INCREMENT BY 1;
SELECT SEQ_BOARDE_NUM.NEXTVAL FROM DUAL;
--확인된 값 : -222
ALTER SEQUENCE SEQ_BOARDE_NUM INCREMENT BY 20;
SELECT SEQ_BOARDE_NUM.NEXTVAL FROM DUAL;
ALTER SEQUENCE SEQ_BOARDE_NUM INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE PRO_BOARDS_INSERT
IS
    VIDX PLS_INTEGER;
    VR BOARDE%ROWTYPE;
BEGIN
    FOR E IN 1..10 LOOP
-- VNUM BOARCE.NUM%TYPE;
        SELECT SEQ_BOARDE_NUM.NEXTVAL INTO VR.NUM FROM DUAL;
        VIDX := VIDX+1;
        VR.WRITER := 'SGAHN'||VIDX;
        VR.SUBJECT := 'SUB' || VIDX || '글';
        VR.EMAIL := 'sg' || VIDX || '@aaa.com';
        
        INSERT INTO BOARDE
        VALUES
        ( VR.NUM,
        VR.WRITER,
        'ASG4785@NAVER.COM',
        'SG SUBJECT',
        'DUCK',
        SYSTIMESTAMP,
        0,
        VR.NUM,
        0,
        0,
        'SG CONTENT',
        'TEMP'
        );
    
    END LOOP;
    
    
END;
/



CREATE OR REPLACE PROCEDURE PRO_BOARDS_INSERT_ANS
IS
    VIDX NUMBER:=0;
    VR BOARDE%ROWTYPE;
    VMAXNUM BOARDE.NUM%TYPE;
BEGIN
        SELECT MAX(NUM) INTO VMAXNUM FROM BOARDE;
        
        WHILE (VIDX <= VMAXNUM) LOOP
        
        SELECT SEQ_BOARDE_NUM.NEXTVAL INTO VR.NUM FROM DUAL;
        VIDX := VIDX+1;
        VR.WRITER := 'SGAHN'||VIDX;
        VR.SUBJECT := 'SUB' || VR.NUM || '글';
        VR.EMAIL := 'SG' || VIDX || '@aaa.com';
        
        INSERT INTO BOARDE
        VALUES
        ( VR.NUM,
        VR.WRITER,
        VR.EMAIL,
        VR.SUBJECT,
        'AAA',
        SYSTIMESTAMP,
        0,
        VIDX,
        1,
        1,
        'SG CONTENT',
        'TEMP'
        );
        VIDX := VIDX+10;
    
    END LOOP;
    
    
END;

/
EXECUTE PRO_BOARDS_INSERT;
EXECUTE PRO_BOARDS_INSERT_ANS;
SELECT * FROM BOARDE;
SELECT * FROM BOARDE ORDER BY REF DESC, RE_STEP ASC;
DELETE FROM BOARDE WHERE NUM=76;

--글쓰기 원본글
INSERT INTO BOARDE VALUES
    (SEQ_BOARDE_NUM.NEXTVAL,
    'KKK',  'AA@AA.COM',    '       RE:RE:SUB,, 글',     'aaa',      SYSTIMESTAMP,   0,
    100,
    1,
    1,
    'sg content',       'TEMP');

--글쓰기 - 댓글
INSERT INTO BOARDE VALUES
    (SEQ_BOARDE_NUM.NEXTVAL,
    'KKK',  'AA@AA.COM',    '       RE:RE:SUB,, 글',     'aaa',      SYSTIMESTAMP,   0,
    3,
    1,
    1,
    'sg content',       'TEMP');
    
SELECT MAX(RE_STEP) FROM BOARDE WHERE REF=62;

UPDATE BOARDE SET RE_STEP = RE_STEP+1 WHERE REF=3 AND NUM<>3 AND RE_STEP > (SELECT RE_STEP FROM BOARDE WHERE NUM =21);

--글쓰기 - 대댓글
-- 댓글의 RE_STEP과 RE_LEVEL을 알아야함
INSERT INTO BOARDE VALUES
    (SEQ_BOARDE_NUM.NEXTVAL,
    'KKK',  'AA@AA.COM',    '       RE:RE:SUB,, 글',     'aaa',      SYSTIMESTAMP,   0,
    62,
    ㅌㅌㅌ,
    2,
    'sg content',       'TEMP');









SELECT * FROM BOARDE;

SELECT * FROM
    (SELECT
    ROWNUM RNUM,
    NUM, SUBJECT, WRITER, TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS'), READCNT, REF, RE_STEP, RE_LEVEL
    FROM 
    --BOARDE
        (SELECT * FROM BOARDE ORDER BY REF DESC, RE_STEP ASC))
    WHERE RNUM BETWEEN 1 AND 30;
    
    SELECT * FROM
			 (SELECT ROWNUM RNUM, NUM, SUBJECT, WRITER, TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS'), READCNT, REF, RE_STEP, RE_LEVEL
			 FROM
			 (SELECT * FROM BOARDE ORDER BY REF DESC, RE_STEP ASC)
			)
			 WHERE RNUM BETWEEN ? AND ?
    

 
-- 작성자 검색        예) 'SG'
SELECT * FROM
    (SELECT ROWNUM RNUM,
    NUM, SUBJECT, WRITER, TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS'), READCNT
    FROM
        (SELECT * FROM BOARDE
        WHERE WRITER LIKE '%SG%'
        ORDER BY REF DESC)
    )
WHERE RNUM BETWEEN 1 AND 10;
-- 제목 검색          예) 'SG'
SELECT * FROM
    (SELECT ROWNUM RNUM,
    NUM, SUBJECT, WRITER, TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS'), READCNT
    FROM
        (SELECT * FROM BOARDE
        WHERE SUBJECT LIKE '%SG%'
        ORDER BY REF DESC)
    )
WHERE RNUM BETWEEN 1 AND 10;
-- 제목 + 내용 검색   예) 'SG'
SELECT * FROM
    (SELECT ROWNUM RNUM,
    NUM, SUBJECT, WRITER, TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS'), READCNT
    FROM
        (SELECT * FROM BOARDE
        WHERE SUBJECT LIKE '%SG%' OR CONTENT LIKE '%SG%'
        ORDER BY REF DESC)
    )
WHERE RNUM BETWEEN 1 AND 10;

--글 읽기  예) 1번 글 읽기
SELECT NUM, SUBJECT, WRITER, READCNT, TO_CHAR(REG_DATE, 'YYYY-MM-DD H24:MI:SS'), CONTENT, EMAIL
FROM BOARDE
WHERE NUM=1;

--글 수정  예) 1번 글 읽기
SELECT SUBJECT, WRITER, CONTENT, EMAIL, PASSWD
FROM BOARDE
WHERE NUM=1;

--방법1: 비밀번호가 맞는지 확인 후 수정 화면으로 가서 PASSWD 수정도 가능
SELECT * FROM BOARDE
WHERE PASSWD = ' ' AND NUM=1;

UPDATE BOARDE SET
SUBJECT = ' ', WRITER = ' ', CONTENT= ' ', EMAIL= ' ', PASSWD= ' '
WHERE NUM=1;

--방법2: 수정화면에서 글쓰기를 누르면 그때 PASSWD 맞다면 수정해줌.
UPDATE BOARDE SET
SUBJECT = ' ', WRITER = ' ', CONTENT= ' ', EMAIL= ' '
WHERE NUM=1 AND PASSWD= ' ';

--글 삭제 예) 2번 글 삭제
SELECT LEVEL FROM BOARDE WHERE NUM = 62; 
SELECT MAX(LEVEL) FROM BOARDE WHERE REF =62i;
--LEVEL = MAX(LEVEL) : 최하위 댓글
DELETE FROM BOARDE WHERE NUM=62;

--LEVEL < MAX(LEVEL) 중간 LEVEL을 가진 댓글
DELETE FROM BOARDE WHERE 
    REF= (SELECT REF FROM BOARD WHERE NUM=62) AND 
    RE_STEP >= (SELECT RE_STEP FROM BOARDE WHERE NUM=62);

--LEVEL : 0 --> 답글 함께 지워준다
DELETE FROM BOARDE WHERE REF=62;









